package com.coremasterkb.serving.observability;

import com.coremasterkb.serving.domain.EvidenceResponse;
import com.coremasterkb.serving.entity.ServingQueryLog;
import com.coremasterkb.serving.mapper.ServingQueryLogMapper;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.*;

/**
 * Writes a record to serving_query_logs after each search request.
 *
 * <p>Called exclusively from {@link QueryLogAspect} -- must never be injected
 * into business code. All failures are swallowed so logging never affects the
 * main response.</p>
 *
 * <p>批次8 R6：结果载体从 ContextPack 换成 {@link EvidenceResponse}（25 号 §5.3）。条目日志
 * 只记公开协议字段（ref/type/truncated/source），不落证据全文——保持行小且不含敏感内容。</p>
 */
@Component
public class QueryLogService {

    private static final Logger log = LoggerFactory.getLogger(QueryLogService.class);
    private static final String FALLBACK_CHANNEL = "prod";

    private final ServingQueryLogMapper logMapper;
    private final ObjectMapper objectMapper = new ObjectMapper();

    public QueryLogService(ServingQueryLogMapper logMapper) {
        this.logMapper = logMapper;
    }

    /**
     * Record a completed (or failed) search invocation.
     *
     * <p>瘦身批次5：入参从 {@code SearchRequest} 收敛为裸标量——HTTP 检索时代的请求 DTO
     * 已退役，日志管道只消费 query/domain/channel 三个字段。</p>
     *
     * @param queryId    UUID generated by the aspect
     * @param query      original query text
     * @param domain     caller domain (blank → "default")
     * @param channel    caller channel (blank → "prod")
     * @param response   assembled evidence response (output); null if pipeline threw or the
     *                   paradigm terminated without {@code assemble}
     * @param durationMs wall-clock time measured by the aspect
     * @param metadata   engine attribution (e.g. {@code engine}, {@code paradigm_id}, {@code has_more})
     */
    public void record(String queryId, String query, String domain, String channel,
                       EvidenceResponse response, long durationMs, Map<String, Object> metadata) {
        try {
            domain = domain != null && !domain.isBlank() ? domain : "default";
            channel = channel != null && !channel.isBlank() ? channel : FALLBACK_CHANNEL;

            ServingQueryLog entry = new ServingQueryLog();
            entry.setId(queryId);
            entry.setDomain(domain);
            entry.setChannel(channel);
            entry.setQueriedAt(Instant.now().toString());
            entry.setDurationMs((int) Math.min(durationMs, Integer.MAX_VALUE));
            entry.setQueryText(query);
            entry.setMetadataJson(toJsonObject(metadata));
            entry.setKeywordsJson("[]");
            entry.setEntitiesJson("[]");
            entry.setScopeJson("{}");
            entry.setResultIssuesJson("[]");
            entry.setResultItemsJson("[]");
            entry.setResultSourcesJson("[]");
            entry.setResultRelationsJson("[]");

            if (response != null) {
                List<EvidenceResponse.EvidenceItem> items = response.evidence();
                boolean hasResult = !items.isEmpty();

                entry.setIntent("evidence");
                entry.setResultItemCount(items.size());
                entry.setResultSeedCount(items.size());
                entry.setResultHasResult(hasResult);
                entry.setResultItemsJson(toJson(buildItemLogs(items)));
                entry.setResultSourcesJson(toJson(buildSourceLogs(items)));
            } else {
                entry.setResultHasResult(false);
            }

            logMapper.insert(entry);

        } catch (Exception e) {
            log.warn("Failed to write query log [{}]: {}", queryId, e.getMessage());
        }
    }

    // -------------------------------------------------------------------------
    // Compact serialization -- text fields excluded to keep rows small
    // -------------------------------------------------------------------------

    private List<Map<String, Object>> buildItemLogs(List<EvidenceResponse.EvidenceItem> items) {
        List<Map<String, Object>> result = new ArrayList<>();
        for (EvidenceResponse.EvidenceItem item : items) {
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("ref", item.ref());
            m.put("type", item.type());
            m.put("truncated", item.truncated());
            if (item.source() != null) {
                m.put("section", item.source().section());
                m.put("file_name", item.source().fileName());
                m.put("document_ref", item.source().documentRef());
            }
            result.add(m);
        }
        return result;
    }

    private List<Map<String, Object>> buildSourceLogs(List<EvidenceResponse.EvidenceItem> items) {
        Set<String> seen = new LinkedHashSet<>();
        List<Map<String, Object>> result = new ArrayList<>();
        for (EvidenceResponse.EvidenceItem item : items) {
            EvidenceResponse.EvidenceSource src = item.source();
            if (src == null) {
                continue;
            }
            String key = String.join("|",
                    nullSafe(src.knowledgeBase()), nullSafe(src.fileName()),
                    nullSafe(src.documentRef()));
            if (!seen.add(key)) {
                continue;
            }
            Map<String, Object> m = new LinkedHashMap<>();
            m.put("knowledge_base", src.knowledgeBase());
            m.put("file_name", src.fileName());
            m.put("document_ref", src.documentRef());
            result.add(m);
        }
        return result;
    }

    private static String nullSafe(String s) {
        return s == null ? "" : s;
    }

    private String toJson(Object obj) {
        if (obj == null) return "[]";
        try {
            return objectMapper.writeValueAsString(obj);
        } catch (JsonProcessingException e) {
            return obj instanceof java.util.Map ? "{}" : "[]";
        }
    }

    /** Like {@link #toJson} but never degrades an object column to "[]" — metadata_json is JSONB. */
    private String toJsonObject(Map<String, Object> map) {
        if (map == null || map.isEmpty()) return "{}";
        try {
            return objectMapper.writeValueAsString(map);
        } catch (JsonProcessingException e) {
            return "{}";
        }
    }
}
